const DISHES = [
  // Soups (6 блюд: 2 рыбных, 2 мясных, 2 вегетарианских)
  {
    keyword: 'tom_yam',
    name: 'Том Ям с креветками',
    price: 365,
    category: 'soup',
    count: '350 мл',
    image: '../images/soup1',
    kind: 'fish',
  },
  {
    keyword: 'norwegian_soup',
    name: 'Норвежский суп',
    price: 270,
    category: 'soup',
    count: '300 мл',
    image: '../images/soup2',
    kind: 'fish',
  },
  {
    keyword: 'borscht',
    name: 'Борщ с говядиной',
    price: 220,
    category: 'soup',
    count: '350 мл',
    image: '../images/soup5',
    kind: 'meat',
  },
  {
    keyword: 'chicken_noodle',
    name: 'Куриный суп с лапшой',
    price: 180,
    category: 'soup',
    count: '320 мл',
    image: '../images/soup6',
    kind: 'meat',
  },
  {
    keyword: 'mushroom_soup',
    name: 'Грибной суп-пюре',
    price: 185,
    category: 'soup',
    count: '330 мл',
    image: '../images/soup3',
    kind: 'veg',
  },
  {
    keyword: 'gazpacho',
    name: 'Гаспачо',
    price: 195,
    category: 'soup',
    count: '350 мл',
    image: '../images/soup4',
    kind: 'veg',
  },

  // Main courses (6 блюд: 2 рыбных, 2 мясных, 2 вегетарианских)
  {
    keyword: 'salmon_steak',
    name: 'Стейк из лосося',
    price: 450,
    category: 'main_course',
    count: '250 г',
    image: '../images/main5',
    kind: 'fish',
  },
  {
    keyword: 'fish_cutlets',
    name: 'Рыбные котлеты с рисом',
    price: 280,
    category: 'main_course',
    count: '300 г',
    image: '../images/main6',
    kind: 'fish',
  },
  {
    keyword: 'lasagna',
    name: 'Лазанья',
    price: 385,
    category: 'main_course',
    count: '250 г',
    image: '../images/main1',
    kind: 'meat',
  },
  {
    keyword: 'beef_stroganoff',
    name: 'Говядина по-строгановски',
    price: 320,
    category: 'main_course',
    count: '300 г',
    image: '../images/main4',
    kind: 'meat',
  },
  {
    keyword: 'chicken_cutlets',
    name: 'Котлеты из курицы с картофельным пюре',
    price: 225,
    category: 'main_course',
    count: '280 г',
    image: '../images/main2',
    kind: 'veg',
  },
  {
    keyword: 'fried_potatoes',
    name: 'Жареная картошка с грибами',
    price: 150,
    category: 'main_course',
    count: '250 г',
    image: '../images/main3',
    kind: 'veg',
  },

  // Salads and starters (6 блюд: 1 рыбный, 1 мясной, 4 вегетарианских)
  {
    keyword: 'ceasar_salad',
    name: 'Цезарь с курицей',
    price: 180,
    category: 'salads',
    count: '200 г',
    image: '../images/salad1',
    kind: 'meat',
  },
  {
    keyword: 'tuna_salad',
    name: 'Салат с тунцом',
    price: 220,
    category: 'salads',
    count: '180 г',
    image: '../images/salad2',
    kind: 'fish',
  },
  {
    keyword: 'greek_salad',
    name: 'Греческий салат',
    price: 160,
    category: 'salads',
    count: '200 г',
    image: '../images/salad3',
    kind: 'veg',
  },
  {
    keyword: 'caprese_salad',
    name: 'Капрезе',
    price: 190,
    category: 'salads',
    count: '150 г',
    image: '../images/salad4',
    kind: 'veg',
  },
  {
    keyword: 'vegetable_platter',
    name: 'Овощная нарезка',
    price: 120,
    category: 'salads',
    count: '250 г',
    image: '../images/salad5',
    kind: 'veg',
  },
  {
    keyword: 'bruschetta',
    name: 'Брускетта с томатами',
    price: 140,
    category: 'salads',
    count: '120 г',
    image: '../images/salad6',
    kind: 'veg',
  },

  // Beverages (6 блюд: 3 холодных, 3 горячих)
  {
    keyword: 'cranberry_morse',
    name: 'Морс клюквенный',
    price: 120,
    category: 'beverages',
    count: '500 мл',
    image: '../images/drink1',
    kind: 'cold',
  },
  {
    keyword: 'orange_juice',
    name: 'Апельсиновый сок',
    price: 90,
    category: 'beverages',
    count: '300 мл',
    image: '../images/drink2',
    kind: 'cold',
  },
  {
    keyword: 'apple_juice',
    name: 'Яблочный сок',
    price: 85,
    category: 'beverages',
    count: '300 мл',
    image: '../images/drink3',
    kind: 'cold',
  },
  {
    keyword: 'green_tea',
    name: 'Зеленый чай',
    price: 60,
    category: 'beverages',
    count: '250 мл',
    image: '../images/drink4',
    kind: 'hot',
  },
  {
    keyword: 'coffee',
    name: 'Кофе американо',
    price: 80,
    category: 'beverages',
    count: '200 мл',
    image: '../images/drink5',
    kind: 'hot',
  },
  {
    keyword: 'herbal_tea',
    name: 'Травяной чай',
    price: 70,
    category: 'beverages',
    count: '250 мл',
    image: '../images/drink6',
    kind: 'hot',
  },

  // Desserts (6 блюд: 3 маленьких, 2 средних, 1 большая)
  {
    keyword: 'tiramisu',
    name: 'Тирамису',
    price: 180,
    category: 'desserts',
    count: '120 г',
    image: '../images/dessert1',
    kind: 'small',
  },
  {
    keyword: 'cheesecake',
    name: 'Чизкейк',
    price: 160,
    category: 'desserts',
    count: '100 г',
    image: '../images/dessert2',
    kind: 'small',
  },
  {
    keyword: 'chocolate_mousse',
    name: 'Шоколадный мусс',
    price: 140,
    category: 'desserts',
    count: '110 г',
    image: '../images/dessert3',
    kind: 'small',
  },
  {
    keyword: 'apple_pie',
    name: 'Яблочный пирог',
    price: 200,
    category: 'desserts',
    count: '150 г',
    image: '../images/dessert4',
    kind: 'medium',
  },
  {
    keyword: 'ice_cream',
    name: 'Мороженое (3 шарика)',
    price: 120,
    category: 'desserts',
    count: '180 г',
    image: '../images/dessert5',
    kind: 'medium',
  },
  {
    keyword: 'chocolate_cake',
    name: 'Шоколадный торт',
    price: 280,
    category: 'desserts',
    count: '200 г',
    image: '../images/dessert6',
    kind: 'large',
  },
];

window.DISHES = DISHES;
